name: Github Actions runner sample on s390x VM
  
on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  workflow-on-s390x:
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: Check the host runner architecture
        run: |
          arch
      - name: ssh into the s390x machine and execute the script
        run: |
          echo -e "Display the bastion machine architecture\n" 
          arch
          rm -rf /root/s390x-runner
          git clone https://github.com/Basavaraju-G/s390x-runner-sample.git /root/s390x-runner
          echo -e "SSH into the s390x VM and execute the script\n"
          ssh root@${{ secrets.S390X_VM_IP }} < /root/s390x-runner/display-runner-arch.sh
